### ISSUE TITLE
Add FPM dependency support for GTK3 branch

### ISSUE THREAD

**Issue by lllaxmatist** [vmagnin/gtk-fortran#282] opened 2024-05-03 10:50 UTC
Please add fpm support to GTK3 branch, so it will be possible to just use GTK3 as fpm dependency.
It is needed to have easy working setup (glade+gtk3+fpm) without much bugs or complex fixing.
For me use of "simplify --3to4" or Cambalache gives no positive result.

**Comment by vmagnin** [comment] 2024-05-03 11:07
I will investigate to see if adding a `fpm.toml` modified with GTK 3 parameters is sufficient. I guess so but I have not touched that branch for long.

**Comment by vmagnin** [comment] 2024-05-03 12:48
Not so simple. The gtk-fortran 4.2 changelog (2022-04-23) states:

> - gtk-fortran can now be used as a simple [fpm](https://fpm.fortran-lang.org) dependency (gtk4 branch only). See the [gtkzero_fpm example](https://github.com/vmagnin/gtkzero_fpm). It implied some changes:
    * `gtk-auto.f90` and `gtkenums-auto.f90` are renamed with the `.inc` extension.
    * Removed `mswindowsonly-auto.f90` and `unixonly-auto.f90`, and added `api_compatibility.f90` with the module `gtk_os_dependent` to keep API compatibility.
    * `plplot/plplot_extra_ndef.f90` renamed `plplot_extra.f90` and moved to `src/`.

I would need to backport in gtk3 a number of small modifications. It needs careful planning. I will think about it but I can not guaranty nor the result nor the time I will spend on it.

**Comment by vmagnin** [comment] 2024-05-04 14:32
I have started working on a development branch:
https://github.com/vmagnin/gtk-fortran/tree/gtk3-dev

The test with fpm will be carried out with:
https://github.com/vmagnin/gtkzero_fpm/tree/gtk3

I will work on it step by step in the next weeks.

**Comment by vmagnin** [comment] 2024-05-05 14:53
@lllaxmatist 
I have finally backported many things from gtk4 branch in the gtk3-dev branch. Can you test it on your system? (MSYS2?) Both with your own programs in the classical way, and also with fpm: start with the gtkzero_fpm repository listed above.

I have regenerated all the Fortran interfaces. Of course, no new functions in GTK 3.24 itself, but you will have especially the latests GLib 2.80.0 and Cairo 1.18.0. See the CHANGELOG.md files for more info.

I will merge gtk3-dev into gtk3, when sufficient testing has been carried out.

**Comment by lllaxmatist** [comment] 2024-05-05 20:24
Ill test it tomorrow on my work setup first thing morning.

**Comment by lllaxmatist** [comment] 2024-05-06 09:44
Did some tests:

gtk3-dev compiles by hand no problems.
    example programs:
    I didn't do extensive testing, just opened them and clicked on random things.
    All runs as should, except these(all fail on start, except hl_list1, that gives 1 line before crash):

        ./hl_list_n
        Program received signal SIGSEGV: Segmentation fault - invalid memory reference.

        ./hl_list_remderers
        Program received signal SIGSEGV: Segmentation fault - invalid memory reference.

        ./hl_list1
        List entry number 1
        Program received signal SIGSEGV: Segmentation fault - invalid memory reference.

        ./hl_tree
        Program received signal SIGSEGV: Segmentation fault - invalid memory reference.

        ./list_demo
        Program received signal SIGSEGV: Segmentation fault - invalid memory reference.

Program gtkzero fpm compiles and runs no problem (did by wiki guide)
Also, i did manual gtkbuilder and gtkbuilder2 compilation as fpm projects, all works well.
But, my own example program gives 
"Could not find signal handler.  Did you compile with -rdynamic?" on all handlers (i did as of gtkbuilder2
 example). I strongly suspect i am doing something wrong myself, but because I am not good developer (just a humble scientist), I cant find my mistake.

**Comment by vmagnin** [comment] 2024-05-06 11:21
Thanks @lllaxmatist for feedback.

Concerning the lists examples, the issue is known and occurs only in MSYS2:
https://github.com/vmagnin/gtk-fortran/issues/244

Concerning your other problem, I will try to answer later when I have time. Is it with fpm? In that case, you could try to use the flag with: `fpm build --flag "-rdynamic"`

**Comment by vmagnin** [comment] 2024-05-06 17:07
At the end of the gtkf-sketcher tutorial, I had noted:
> Compile and execute the example application:
$ gfortran example.f90 -o example $(pkg-config --cflags --libs gtk-3-fortran)
$ ./example
    You can see a basic application with three buttons: Button1, Button2, Exit. Of course, you will see some warnings like `(example:12807): Gtk-WARNING **: 15:06:45.542: Could not find signal handler 'destroy'.  Did you compile with -rdynamic?` and the GUI does nothing because you now need to add code to manage each event into the specified files.

Concerning that flag:
> -rdynamic
	Pass the flag -export-dynamic to the ELF linker, on targets that support it. This instructs the linker to add all symbols, not only used ones, to the dynamic symbol table. This option is needed for some uses of dlopen or to allow obtaining backtraces from within a program.
	
See also: https://github.com/vmagnin/gtk-fortran/issues/180

When you build gtk-fortran with CMake, CMake is writting the linker flags (`CMAKE_EXE_LINKER_FLAGS`) into the file `src/gtk-fortran.pc.in` that will be installed in the system and used by pgkconfig:
```bash
$ pkg-config --cflags --libs gtk-4-fortran
-rdynamic -I/usr/local/include/gtk-4-fortran..................
```

@lllaxmatist Does using `fpm build --flag "-rdynamic"` works for you?
Note that it does not seem possible to include that option into a `fpm.toml` (but I am not sure).

**Comment by lllaxmatist** [comment] 2024-05-07 08:18
> @lllaxmatist Does using `fpm build --flag "-rdynamic"` works for you? Note that it does not seem possible to include that option into a `fpm.toml` (but I am not sure).

Nope. But i suspect it is a problem with me and using glade(or code) wrong. 
If i create new fpm project, copy-paste code from gtkbuilder (or gtkbulder2) into main.f90 and add the gtkbuilder.glade file it works fine just like that. With all callbacks working no problem.

**Comment by lllaxmatist** [comment] 2024-05-07 10:17
FOUND IT!!!!

It has something to do with how fortran handles uppercase.
If you have for example
`on_windowdestroy`
 it will work fine, but if you have
 `on_windowDestroy` 
 you will get  "Could not find signal handler." error.
 (and no, i had the same-case letters in code and in glade)
 
 Maybe add that info into wiki?

**Comment by vmagnin** [comment] 2024-05-07 10:36
Interesting. Fortran is not case sensitive but C is. If `on_windowDestroy()` is a callback function (therefore called by the C side), problems could occur. I think the Fortran compiler is using internally `on_windowdestroy()` and C is calling `on_windowDestroy()` (as written in Glade).

Note that you could also try to use the `name` parameter of the `bind(c)` attribute:
```fortran
function on_windowDestroy() bind(c, name="on_windowDestroy")
```
or
```fortran
function on_windowdestroy() bind(c, name="on_windowDestroy")
```
Both should work.

**Comment by lllaxmatist** [comment] 2024-05-07 10:50
It seems so.
I just tested it with `on_windowDestroy` in code, but `on_windowdestroy` in glade and it is working.

and `name=` is not helping btw

Anyway it is not a big issue, just_use_snake_case

**Comment by vmagnin** [comment] 2024-05-08 09:09
I have merged the branch `gtk3-dev` in `gtk3`.
See the https://github.com/vmagnin/gtk-fortran/blob/gtk3/CHANGELOG.md for all changes.

The [gtkzero_fpm](https://github.com/vmagnin/gtkzero_fpm/tree/gtk3) example is now using that branch.

**Closed as completed by vmagnin** 2024-05-08 09:09 UTC
Labels: Feature request, GTK 3
